
require 'omf_sfa'
module OMF::SFA
  module Resource; end
end

require 'omf-sfa/resource/gurn'
require 'omf-sfa/resource/constants'
require 'omf-sfa/resource/oresource'
require 'omf-sfa/resource/oproperty'
require 'omf-sfa/resource/ocomponent'
require 'omf-sfa/resource/ogroup'
require 'omf-sfa/resource/group_membership'
require 'omf-sfa/resource/account'
require 'omf-sfa/resource/lease'
require 'omf-sfa/resource/component_lease'
require 'omf-sfa/resource/ip'
require 'omf-sfa/resource/interface'
require 'omf-sfa/resource/location'
require 'omf-sfa/resource/channel'
require 'omf-sfa/resource/link'
require 'omf-sfa/resource/disk_image'
require 'omf-sfa/resource/sliver_type'
require 'omf-sfa/resource/node'
require 'omf-sfa/resource/chasis_manager_card'
require 'omf-sfa/resource/group_component'
require 'omf-sfa/resource/project_membership'
require 'omf-sfa/resource/project'
require 'omf-sfa/resource/sfa_base'
require 'omf-sfa/resource/user'
require 'omf-sfa/resource/cpu'
require 'omf-sfa/resource/e_node_b'
require 'omf-sfa/resource/openflow_switch'
require 'omf-sfa/resource/wimax_base'
